### ISSUE TITLE
生成Verilog时出现的问题

### ISSUE THREAD

**Issue by 1997xu** [THU-DSP-LAB/ventus-gpgpu#49]
您好，IDE生成Verilog时，报了俩错：
1 .scala: Error: Error compiling the sbt component 'compiler-bridge-2.12.15-66.0'
sbt.internal.inc.CompileFailed: Error compiling the sbt component 'compiler-bridge-2.12.15-66.0'
	at sbt.internal.inc.AnalyzingCompiler$.handleCompilationError$1(AnalyzingCompiler.scala:436)
	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$5(AnalyzingCompiler.scala:453)
	at sbt.internal.inc.AnalyzingCompiler$.$anonfun$compileSources$5$adapted(AnalyzingCompiler.scala:448)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:488)
2. scala: Error: org.jetbrains.jps.incremental.scala.remote.ServerException
java.lang.StackOverflowError
	at scala.runtime.Statics.anyHash(Statics.java:127)
	at scala.util.hashing.MurmurHash3.listHash(MurmurHash3.scala:285)
	at scala.util.hashing.MurmurHash3$.seqHash(MurmurHash3.scala:355)
	at scala.collection.Seq.hashCode(Seq.scala:41)
	at scala.collection.Seq.hashCode$(Seq.scala:41)
	at scala.collection.AbstractSeq.hashCode(Seq.scala:1190)

查了查是关于Jdk版本问题，请问你们会遇到这个问题吗，你们使用的JDK版本是什么呢？

**Comment by reoLantern** [comment]
平时使用的版本是jdk 11
